export const PRODUCTION_VOL_MONTH = 'PRODUCTION_VOL_MONTH';
export const PRODUCTION_VOL_SUM = 'PRODUCTION_VOL_SUM';
export const PRODUCTION_RATIO_HANDLER = 'PRODUCTION_RATIO_HANDLER';

export const EMPOLOYER_AMOUNT_HANDLER = 'EMPOLOYER_AMOUNT_HANDLER';
