export const PRODUCTION_VOL_MONTH = 'PRODUCTION_VOL_MONTH';
export const PRODUCTION_VOL_SUM = 'PRODUCTION_VOL_SUM';
export const PRODUCTION_RATIO_HANDLER = 'PRODUCTION_RATIO_HANDLER';

export const EMPOLOYER_AMOUNT_HANDLER = 'EMPOLOYER_AMOUNT_HANDLER';

export const EMPOLOYER_SALARY = 'EMPOLOYER_SALARY';
export const INCOMES_PER_MONTH = 'INCOMES_PER_MONTH';
export const TAX_MONTH = 'TAX_MONTH';
export const NET_INCOMES_MONTH = 'NET_INCOMES_MONTH';
